"""create initial tables

Revision ID: 4a78ffa1b6c5
Revises: 
Create Date: 2026-03-17 19:29:20.908357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a78ffa1b6c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_names',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_names_server_id'), 'channel_names', ['server_id'], unique=False)
    op.create_table('voice_channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_channels_owner_id'), 'voice_channels', ['owner_id'], unique=False)
    op.create_index(op.f('ix_voice_channels_server_id'), 'voice_channels', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_channels_server_id'), table_name='voice_channels')
    op.drop_index(op.f('ix_voice_channels_owner_id'), table_name='voice_channels')
    op.drop_table('voice_channels')
    op.drop_index(op.f('ix_channel_names_server_id'), table_name='channel_names')
    op.drop_table('channel_names')
    # ### end Alembic commands ###
