"""add default channel limit

Revision ID: a912a43663a5
Revises: 17967282c188
Create Date: 2026-03-23 21:33:22.897434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a912a43663a5'
down_revision: Union[str, Sequence[str], None] = '17967282c188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_settings', sa.Column('default_user_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_settings', 'default_user_limit')
    # ### end Alembic commands ###
